server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      # eureka服务地址，如果为集群，需指定其他地址
      defaultZone: http://127.0.0.1:10086/eureka #,http://127.0.0.1:10087/eureka
    #是否注册自己为服务
    register-with-eureka: false
    #不拉取服务--因为不消费
    fetch-registry: false
  server:
    #剔除已经失效服务的间隔时间 ms 【每60s会执行将已经90s没有续约的服务剔除】
    eviction-interval-timer-in-ms: 6000
    #是否打开自我保护【默认true】
    enable-self-preservation: true